baseURL = "https://dayu.me/"
languageCode = "zh-CN"
title = "你好，大余"
theme = "tale"
defaultContentLanguage = "zh"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "关于"
    title = "关于"
    url = "/about/"
    weight = 0
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    title = "文章"
    url = "/posts/"
    weight = 0